[client]
# Change the visibility of items in the toolbar, options menu,
# and settings dialog (top right of the app).

# Allowed values:
# * "auto" : Show the developer options if the app is accessed through
# localhost or through Streamlit Community Cloud as a developer.
# Hide them otherwise.
# * "developer" : Show the developer options.
# * "viewer" : Hide the developer options.
# * "minimal" : Show only options set externally (e.g. through
# Streamlit Community Cloud) or through st.set_page_config.
# If there are no options left, hide the menu.

# Default: "auto"
toolbarMode = "minimal"


[server]
# Automatically rerun script when the file is modified on disk.
runOnSave = true

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 5

[browser]
# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor="#bd93f9"

# Background color for the main content area.
backgroundColor="#282a36"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor="#44475a"

# Color used for almost all text.
textColor="#f8f8f2"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"